#################################################
# Work configuration for Hammerflow
# This configuration is prioritized over sample.toml
# when loaded in init.lua
#################################################

# settings
leader_key = "f18"        # leader key that starts the sequence
leader_key_mods = ""      # optional modifiers
auto_reload = true        # reload when config files change
toast_on_reload = false   # show toast on reload
show_ui = true            # show the UI with key maps
key_maps_per_line = 3     # number of key maps per line

# Quick app access
t = "Wezterm"
m = "Mail"
z = "Zen"
o = "Obsidian"


# New content
[n]
label = "[new]"
t = "hs:hs.application.launchOrFocus('Zen'); hs.timer.doAfter(0.2, function() hs.eventtap.keyStroke({'cmd'}, 't') end)"
n = "hs:hs.application.launchOrFocus('Obsidian'); hs.timer.doAfter(0.5, function() hs.eventtap.keyStroke({'cmd'}, 'n') end)"


# Hammerspoon management
[h]
label = "[hammerspoon]"
c = "code: ~/.hammerspoon"
r = "reload"
