#################################################
# Work configuration for Hammerflow
# This configuration is prioritized over sample.toml
# when loaded in init.lua
#################################################

# settings
leader_key = "f18"       # leader key that starts the sequence
leader_key_mods = ""     # optional modifiers
auto_reload = true        # reload when config files change
toast_on_reload = false   # show toast on reload
show_ui = true            # show the UI with key maps
key_maps_per_line = 4     # number of key maps per line

# Quick app access
t = ["Wezterm", "terminal"]
m = ["Mail", "mail"]
n = ["Obsidian", "notes"]
h = ["raycast://extensions/raycast/clipboard-history/clipboard-history", "clipboard"]
b = ["Brave Browser", "browser"]
c = ["ChatGPT", "chat"]
f = ["Finder", "files"]


# Text pasting
[i]
label = "me"
m = ["hs:hs.pasteboard.setContents('s.goeuriot@cosnova.com'); hs.eventtap.keyStroke({'cmd'}, 'v')", "mail"]
p = ["hs:hs.pasteboard.setContents('new4stphn!'); hs.eventtap.keyStroke({'cmd'}, 'v')", "pass"]

# Post mode
[p]
label = "post"
b = ["hs:hs.execute('open -a \"Bluesky\"')", "bluesky"]
m = ["hs:hs.execute('open -a \"Mastodon\"')", "mastodon"]

# Raycast shortcuts
[r]
label = "raycast"
c = ["raycast://extensions/raycast/raycast/confetti", "confetti"]
e = ["raycast://extensions/raycast/emoji-symbols/search-emoji-symbols", "emoji"]
h = ["raycast://extensions/raycast/clipboard-history/clipboard-history", "clipboard"]
f = ["raycast://extensions/raycast/system/hide-all-apps-except-frontmost", "hide others"]
u = ["raycast://extensions/raycast/system/unhide-all-hidden-apps", "unhide all"]
